---
- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install requirements
  ansible.builtin.package:
    name: "{{ sysctl_requirements }}"
    state: present

- name: Set sysctl setting
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ sysctl_set }}"
    state: "{{ item.state | default('present') }}"
    reload: "{{ sysctl_reload }}"
    sysctl_file: "{{ sysctl_file }}"
  loop: "{{ sysctl_items }}"
  when:
    - sysctl_items is defined
    - item.name is defined
    - item.value is defined
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
  loop_control:
    label: "{{ item.name }}"
